name: Build and Deploy Go API App

on:
  push:
    branches:
      - master   # Change this to your main branch name
    # paths:
    #   - 'backend' 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'   # Change this to your desired Go version

    - name: Build the Go API app
      run: go build -o api   # Change the binary name if necessary

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "backend/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_BE_TARGET }}

    - name: Restart Remote Service
      run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sudo systemctl restart audiobytesBE.service"
