name: Build and Deploy Go API App

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'   # Change this to your desired Go version

    - name: Build the Go API app
      run: go build -o api   # Change the binary name if necessary

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "backend/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_BE_TARGET }}

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: sudo systemctl restart audiobytesBE.service

    # - name: Restart Remote Service
    #   run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sudo systemctl restart audiobytesBE.service"
