name: Build and Deploy React App

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18   # Change this to your desired Node.js version

    # - name: Install dependencies
    #   run: npm install

    # - name: Build the React app
    #   run: npm run build   # Change this if you use a different build command

    - name: test
      run: ls

    # - name: Deploy to server
    #   uses: easingthemes/ssh-deploy@v4.1.8
    #   with:
    #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #     TARGET: ${{ secrets.REMOTE_TARGET }}  # Use SSH key if possible
